name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2-beta
      with:
        go-version: 1.19
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Build
      run: make build
